In [3]:
import numpy as np
import pandas as pd

## Constant Variables

In [45]:
item_file = 'ml-100k/u.item'
user_rating_train_file = 'ml-100k/ua.base'
user_rating_test_file = 'ml-100k/ua.test'
user_file = 'ml-100k/u.user'

## Load items

In [51]:
item_columns = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [52]:
item_data = pd.read_csv(item_file, sep='|', encoding='latin-1', names=item_columns)
item_data

movie id                                movie title release date  \
0            1                           Toy Story (1995)  01-Jan-1995   
1            2                           GoldenEye (1995)  01-Jan-1995   
2            3                          Four Rooms (1995)  01-Jan-1995   
3            4                          Get Shorty (1995)  01-Jan-1995   
4            5                             Copycat (1995)  01-Jan-1995   
...        ...                                        ...          ...   
1677      1678                          Mat' i syn (1997)  06-Feb-1998   
1678      1679                           B. Monkey (1998)  06-Feb-1998   
1679      1680                       Sliding Doors (1998)  01-Jan-1998   
1680      1681                        You So Crazy (1994)  01-Jan-1994   
1681      1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video release date                                           IMDb URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [17]:
item_matrix = item_data.as_matrix()[:, -19:]
item_matrix

/Users/datnguyen/Documents/Git/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

## Load user

In [25]:
user_columns = ['id', 'age', 'gender', 'occupation', 'post office code']

In [28]:
user_data = pd.read_csv(user_file, encoding='latin-1', sep='|', names=user_columns)
user_data

id  age gender     occupation post office code
0      1   24      M     technician            85711
1      2   53      F          other            94043
2      3   23      M         writer            32067
3      4   24      M     technician            43537
4      5   33      F          other            15213
..   ...  ...    ...            ...              ...
938  939   26      F        student            33319
939  940   32      M  administrator            02215
940  941   20      M        student            97229
941  942   48      F      librarian            78209
942  943   22      M        student            77841

[943 rows x 5 columns]

In [29]:
user_matrix = user_data.as_matrix()
user_matrix

/Users/datnguyen/Documents/Git/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[1, 24, 'M', 'technician', '85711'],
       [2, 53, 'F', 'other', '94043'],
       [3, 23, 'M', 'writer', '32067'],
       ...,
       [941, 20, 'M', 'student', '97229'],
       [942, 48, 'F', 'librarian', '78209'],
       [943, 22, 'M', 'student', '77841']], dtype=object)

## Load rating data

In [40]:
rating_columns = ['user_id', 'movie_id', 'rating', 'timestamp']

In [43]:
rating_train_data = pd.read_csv(user_rating_train_file, encoding='latin-1', sep='\t', names=rating_columns)
rating_train_data

user_id  movie_id  rating  timestamp
0            1         1       5  874965758
1            1         2       3  876893171
2            1         3       4  878542960
3            1         4       3  876893119
4            1         5       3  889751712
...        ...       ...     ...        ...
90565      943      1047       2  875502146
90566      943      1074       4  888640250
90567      943      1188       3  888640250
90568      943      1228       3  888640275
90569      943      1330       3  888692465

[90570 rows x 4 columns]

In [46]:
rating_train_matrix = rating_train_data.as_matrix()
rating_train_matrix

/Users/datnguyen/Documents/Git/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[        1,         1,         5, 874965758],
       [        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]])

In [123]:
rating_test_data = pd.read_csv(user_rating_test_file, encoding='latin-1', names=rating_columns, sep='\t')
rating_train_data

user_id  movie_id  rating  timestamp
0            1         1       5  874965758
1            1         2       3  876893171
2            1         3       4  878542960
3            1         4       3  876893119
4            1         5       3  889751712
...        ...       ...     ...        ...
90565      943      1047       2  875502146
90566      943      1074       4  888640250
90567      943      1188       3  888640250
90568      943      1228       3  888640275
90569      943      1330       3  888692465

[90570 rows x 4 columns]

In [122]:
rating_test_matrix = rating_train_data.as_matrix()
rating_test_matrix

/Users/datnguyen/Documents/Git/env/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[        1,         1,         5, 874965758],
       [        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]])

## Build contentbase algorithm 

In [106]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import Ridge

In [152]:
tfidf = TfidfTransformer().fit_transform(item_matrix)

In [153]:
tfidf = tfidf.toarray()
tfidf.shape[1]

19

In [270]:
def get_rating_by_user_id(user_id, rating_matrix):
    data = rating_matrix[rating_matrix[:, 0] == user_id]
    rating = data[:, 2]
    movie_ids = data[:, 1]
    
    return np.array(rating), np.array(movie_ids)

In [271]:
n_users = user_matrix.shape[0]
n_users

943

In [272]:
X = np.empty((n_users, item_matrix.shape[1]))

In [273]:
W = np.empty((item_matrix.shape[1], n_users))

In [274]:
b = np.empty((1, n_users))

In [275]:
rigde = Ridge(alpha=0.01, fit_intercept=True)

In [281]:
for i in range(n_users):
    user_id = i + 1
    rating, movie_ids = get_rating_by_user_id(user_id, rating_train_matrix)
#     print(movie_ids)
#   print(rating, movie_ids)
#   movies = item_matrix[movie_ids]
#   x = tfidf.transform(movies).toarray()
    x = tfidf[np.subtract(movie_ids, 1)]
#     print(x)
#     X[i, :] = tfidf[movie_ids]
    rigde.fit(x, rating)
    W[:, i] = rigde.coef_
    b[0, i] = rigde.intercept_
#     print(rigde.coef_)

In [282]:
W

array([[ 0.99684214,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.3317665 ,  3.53859123,  0.93058638, ..., -5.71573277,
         0.02855827,  0.50472501],
       [-0.42307992,  0.9908748 ,  2.29031008, ..., -6.45095073,
         1.36196632, -0.17880425],
       ...,
       [ 0.48984917,  1.44921384, -0.08445488, ..., -2.18229564,
         0.71509069,  0.5628234 ],
       [ 0.23986971,  0.96714621,  0.92097721, ...,  0.        ,
         0.75566308,  0.36875069],
       [ 0.71575517,  0.        ,  0.        , ...,  0.        ,
         0.9206785 , -0.75671318]])

In [283]:
def calculate_rating(user_id, movie_id):
    rating = np.dot(W.T[user_id], tfidf[movie_id]) + b[0][user_id -1]
    true_label = rating_test_matrix[rating_test_matrix[:, 0] == user_id][:, 2][movie_id-1]
    
    print(rating, true_label)
    return rating, true_label

In [284]:
calculate_rating(1, 1)

6.3155088910608175 5


(6.3155088910608175, 5)

In [285]:
W.shape

(19, 943)

In [286]:
rating_test_matrix[rating_test_matrix[:, 0] == 1][:, 2][0]

5

In [287]:
W.T.shape

(943, 19)

In [288]:
Y_prediction = np.dot(tfidf, W) + b

In [289]:
Y_prediction.shape

(1682, 943)

## Evaluate

In [300]:
#Using mean square error to evaluate model

def evaluate_model(W, b, rating_matrix, y_prediction):
    se = 0
    cnt = 0
    
    for i in range(n_users):
        rating, movie_ids = get_rating_by_user_id(i+1, rating_test_matrix)
        e = rating - y_prediction.T[i, np.subtract(movie_ids, 1)]
        se += (e*e).sum(axis=0)
        cnt += e.size

    return np.sqrt(se/cnt)

In [301]:
item_matrix.shape

(1682, 19)

In [302]:
evaluate_model(W, b, rating_test_matrix, Y_prediction)

0.908980456282672